// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    maps\mp\mp_zombie_windmill_precache::main();
    maps\createart\mp_zombie_windmill_art::main();
    maps\mp\mp_zombie_windmill_fx::main();
    level thread maps\mp\_utility::_id_6F74( ::mute_audio_on_intro );
    _id_0483::main();
    maps\mp\mp_zombie_windmill_lighting::main();
    maps\mp\mp_zombie_windmill_aud::main();
    maps\mp\mp_zombie_windmill_util::map_start_utilities();
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode::init_sg();
    level._id_ACA3 = 1;
    level._id_323A = 1;
    level._id_ABD3 = -3500;
    level._id_0C11 = 0;
    _id_0472::_id_8A2F( "compass_map_mp_zombie_windmill" );
    game["attackers"] = "allies";
    game["defenders"] = "axis";
    level.initnewzombietypes = ::init_new_zombie_types;
    thread maps\mp\zombies\shotgun\_zombies_shotgun_gamemode::shotgun_classic_init();
    init_windmill_sg();
    register_windmill_sg_objectives();
    level.sg_pack_use_small_radius = 1;
    level._id_AC71 = ::initwindmillweapons;
    level._id_783F = 0;
    level.door_data_out_of_date = 0;
    level.disable_jumpscare_playerdata = 0;
    level._id_AC14 = 0;
    level._id_ACA3 = 1;
    level._id_323A = 1;
    level.reworkedconsumabledenabled = 1;
    level.loot_pap_camo_ref_override = "zom_amp_05";
    level.pap_camo_ref_override = "zom_frontline_01";
    _func_032( "ui_zm_intermission_swaptime_1", 6 );
    _func_032( "ui_zm_intermission_swaptime_2", 2 );
    setdvar( "2494", "0.12, 0, 0" );
    common_scripts\utility::flag_init( "power_sz2" );
    _id_5375();
    thread maps\mp\mp_zombie_windmill_code::ee_init();
    level thread _id_3FD2();
    level thread add_windmill_ceiling_patch();
    level thread intro_special_zombies_init();
    maps\mp\zquests\zmb_secret_challenges_util::init_challenges_utility();
    level thread maps\mp\zquests\dlc3_secrets_mp_zombie_windmill::init_dlc3_secrets_mp_zombie_windmill();
    thread performance_stuff();
}

mute_audio_on_intro()
{
    self _meth_8626( "windmill_intro_movie" );

    while ( !level.gamehasstarted )
    {
        self freezecontrols( 1 );
        self _meth_812B( 0 );
        self _meth_8324();
        self _meth_84CB();
        waitframe();
    }

    self freezecontrols( 0 );
    self _meth_812B( 1 );
    self _meth_8325();
    self _meth_84CC();
    self _meth_8627( "windmill_intro_movie" );
}

_id_3FD2()
{
    level waittill( "player_spawned", var_0 );
    thread maps\mp\mp_zombie_windmill_code::audio_log_init();
}

initwindmillweapons()
{
    level thread maps\mp\zombies\shotgun\_zombies_shotgun_gamemode::initialize_common_sg_weapons();
}

_id_5375()
{
    _id_055A::init();
    _id_055A::_id_530A( "zone_plaza", 1 );
    _id_055A::_id_088A();
    thread house_door_listener();
}

init_new_zombie_types()
{
    maps\mp\zombies\zombie_sizzler::init();
}

house_door_listener()
{
    common_scripts\utility::flag_init( "zone_plaza_to_zone_house" );
    common_scripts\utility::_id_3C9F( "zone_plaza_to_zone_house" );

    foreach ( var_1 in level._id_AC1D )
    {
        if ( isdefined( var_1._id_819A ) && var_1._id_819A == "zone_plaza_to_zone_house" && ( !isdefined( var_1._id_6BE1 ) || !var_1._id_6BE1 ) )
            var_1 notify( "open", undefined );
    }
}

init_windmill_sg()
{
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::basic_escort_init();
    maps\mp\zombies\shotgun\_zombies_shotgun_obj_blimp_attack::sg_init_obj_blimp_attack();
}

add_windmill_ceiling_patch()
{
    var_0 = common_scripts\utility::_id_46B7( "ceiling_stuff_patches_05", "targetname" );
    var_1 = common_scripts\utility::_id_46B7( "ceiling_stuff_patches_04", "targetname" );

    foreach ( var_3 in var_0 )
    {
        var_4 = spawn( "script_model", var_3.origin );
        var_4.angles = var_3.angles;
        var_4 setmodel( "cob_floor_dmg_section_wood_05" );
    }

    foreach ( var_3 in var_1 )
    {
        var_4 = spawn( "script_model", var_3.origin );
        var_4.angles = var_3.angles;
        var_4 setmodel( "cob_floor_dmg_section_wood_04" );
    }
}

register_windmill_sg_objectives()
{
    var_0 = _func_18E( "bubble_boy_sheild", "targetname" );
    var_0 _meth_82C2();
    var_1 = [];
    var_1["type_extermination_common"] = spawnstruct();
    var_1["type_extermination_common"]._id_2A35 = spawnstruct();
    var_1["type_extermination_common"]._id_2A35.ext_type = [ [ "zombie_exploder" ], [ "zombie_generic" ] ];
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode::include_shotgun_v1_common_objectives( var_1 );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::sg_obj_register( "wb_blimp_attack", "blimp_attack", [ 6 ] );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::sg_obj_register( "escort", "type_escort", [ 6 ], 120, undefined, 1, ::objective_escort_success );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::sg_obj_register( "windmill_boss", "type_boss", [ 10 ], 300, ::run_bubble_boy );
    maps\mp\zombies\sg_events_v1\_options::create_option( "keypoint_interact_repair_common_radios", maps\mp\zombies\shotgun\_zombies_shotgun_radio_table_util::set_repair_trigs_to_radio_table_type );
    maps\mp\zombies\sg_events_v1\_options::set_option( "keypoint_interact_repair_common", "keypoint_interact_repair_common_radios" );
}

________fireman_boss_logic_________()
{

}

run_bubble_boy( var_0 )
{
    var_1 = _func_18E( "bubble_boy_sheild", "targetname" );

    foreach ( var_3 in _id_0547::_id_408F() )
        var_3 suicide();

    level thread pause_wave_for_a_moment();
    waitframe();
    var_5 = common_scripts\utility::_id_46B5( "sg_boss_spawnpoint", "targetname" );
    var_6 = _id_0564::_id_3C11( 0, var_5, 0 );
    var_6 maps\mp\zombies\sg_events_v1\_boss_util::set_zombie_boss_has_weapon_loot();
    var_6 _id_0547::_id_84CB();
    var_6.scaleshealthbyplayers = 1;
    var_6.bombsabotagefunc = ::bombsabotagefunc;
    var_6.shortstun = 1;
    var_6._id_57FD = 1;
    var_7 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "type_boss_health" );
    var_7 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_modified_boss_health( var_7 );
    var_6.isuberfireman = int( maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_player_level_setting( "zmb_fireman_boss_is_uber" ) );

    if ( common_scripts\utility::_id_562E( var_6.isuberfireman ) )
        level thread maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::spawn_extra_redskull_assassins( "zombie_assassin_shellshock" );

    var_6 maps\mp\agents\_agent_common::_id_83FD( int( var_7 ) );
    var_6.no_kill_on_skip = 1;
    var_6.godtank = 1;
    var_1.origin = var_6 gettagorigin( "J_SpineUpper" );
    var_1 linktosynchronizedparent( var_6, "J_SpineUpper" );
    var_1 _meth_82C1();
    var_1 thread maps\mp\gametypes\_damage::_id_8676( 99999999 );
    var_1.health = 99999999;
    var_1.damagecallback = ::show_feedback;
    var_6.myshield = var_1;
    var_6 thread maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::show_sh_boss_health( -20 );
    var_6.sgboss = 1;
    level thread drop_bombs_loop( var_6 );
    waitframe();
    var_6 thread handle_fireman_pommel_upgrade();
    level.fireman_boss = var_6;
    var_8 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::basic_boss_waitfor_defeated();
    level notify( "fireman_boss_has_died" );
    level.fireman_boss_has_died = 1;
    var_1 delete();

    if ( common_scripts\utility::_id_562E( var_8 ) )
    {
        foreach ( var_10 in level.players )
        {
            var_11 = _id_0547::_id_4745( var_10, "totalBossDefeats" );
            var_11++;
            var_10 setplayerdata( common_scripts\utility::_id_46A8(), "totalBossDefeats", var_11 );
        }

        common_scripts\utility::flag_set( "zmb_players_gamemode_boss_defeated" );
    }

    return common_scripts\utility::_id_562E( var_8 );
}

show_feedback( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    if ( !isdefined( self.lastspark ) )
        self.lastspark = gettime();

    if ( gettime() - self.lastspark < 100 )
        return;

    var_12 = vectortoangles( var_6 - self.origin );
    self.lastspark = gettime();
    var_13 = 0;

    if ( _id_0547::_id_5565( var_4, "MOD_EXPLOSIVE" ) )
        var_13 = 1;

    if ( _id_0547::_id_5565( var_4, "MOD_EXPLOSIVE_BULLET" ) )
        var_13 = 1;

    if ( issubstr( var_5, "m1911_pap_zm" ) )
        var_13 = 1;

    if ( issubstr( var_5, "dp28_pap_zm" ) && _id_0547::_id_5565( var_4, "MOD_EXPLOSIVE" ) )
        var_13 = 2;

    if ( issubstr( var_5, "fliegerfaust" ) )
        var_13 = 4;

    if ( issubstr( var_5, "panzerschreck_zm" ) )
        var_13 = 5;

    if ( issubstr( var_5, "bazooka_zm" ) )
        var_13 = 5;

    if ( !isdefined( self.damagepoints ) )
        self.damagepoints = 0;

    self.damagepoints = self.damagepoints + var_13;

    if ( var_13 > 0 && isdefined( var_1 ) && isplayer( var_1 ) )
        var_1 thread _id_04C7::_id_A102( "minor" );

    if ( self.damagepoints >= 20 )
    {
        self.damagepoints = 0;

        foreach ( var_15 in _id_0547::_id_408F() )
        {
            if ( _id_0547::_id_5565( var_15._id_0A4B, "zombie_fireman" ) )
                var_15 notify( "break_shield_now" );
        }
    }

    if ( !_id_0547::_id_585C( _id_0547::_id_AAF9( var_5 ) ) )
    {
        playfx( common_scripts\utility::_id_44F5( "fireman_sparks" ), var_6, anglestoforward( var_12 ), anglestoup( var_12 ) );
        playfx( common_scripts\utility::_id_44F5( "zmb_mm_tracer_p38" ), var_6, anglestoforward( var_12 ), anglestoup( var_12 ) );
    }
}

enable_shields()
{
    self.myshield _meth_82C1();
    self._id_480F = 1;

    if ( isdefined( self.myshieldfx ) )
        return;

    _id_0378::_id_8D74( "dlc3_fireman_enable_shield", self );
    var_0 = _func_2A8( common_scripts\utility::_id_44F5( "zmb_snipe_boss_energy_field" ), self, "J_Spine4" );
    maps\mp\agents\_agent_utility::deleteentonagentdeath( var_0 );
    _func_14C( var_0 );
    self.myshieldfx = var_0;
}

handle_fireman_pommel_upgrade()
{
    self endon( "death" );
    childthread electro_burst_players();
    wait 1.45;
    playfx( common_scripts\utility::_id_44F5( "zmb_snipe_boss_energy_field_burst" ), self gettagorigin( "J_Spine4" ), anglestoforward( self.angles ) );
    childthread handle_shield();
}

handle_shield()
{
    self.myshield _meth_82C3( 1 );

    for (;;)
    {
        var_0 = 0;
        enable_shields();
        self waittill( "break_shield_now" );
        self.myshield.damagepoints = 0;
        disable_shields();
        wait( maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "zmb_fireman_boss_shield_downtime" ) );
    }
}

electro_burst_players()
{
    _id_0547::_id_A6F6();

    for (;;)
    {
        foreach ( var_1 in level.players )
        {
            if ( isdefined( var_1.lastfiremanpush ) && ( gettime() - var_1.lastfiremanpush ) / 1000 < 4 )
                continue;

            if ( isdefined( self.myshieldfx ) && distance( self.origin, var_1.origin ) < 120 )
            {
                var_1.lastfiremanpush = gettime();
                var_1 maps\mp\zombies\zombie_assassin_basic::run_shellshock( 2, 1, self.origin, 550 );
                _id_0380::_id_2889( "zmb_mystery_box_elec", undefined, var_1.origin );
            }
        }

        waitframe();
    }
}

disable_shields()
{
    self endon( "death" );
    self._id_480F = 0;
    playfx( common_scripts\utility::_id_44F5( "stunning_burst_aoe" ), self.origin );
    _id_0378::_id_8D74( "dlc3_fireman_disable_shield", self );

    if ( isdefined( self.myshieldfx ) )
    {
        _id_053A::mini_stunning_burst_execute( self.origin, self, 500, 0.2 );
        self.myshieldfx delete();
    }

    self.myshield _meth_82C2();
}

bombsabotagefunc( var_0, var_1, var_2 )
{
    self notify( "break_shield_now" );
    waitframe();
    var_3 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "type_boss_health" );
    var_3 = int( var_3 / level.players.size / 4 );
    self _meth_8059( var_3, var_0.origin, var_0, var_0, var_2, var_1 );
}

______extra_boss_logic_bombers____()
{

}

drop_bombs_loop( var_0 )
{
    level endon( "fireman_boss_has_died" );
    var_1 = getentarray( "origin_boss_airstrike_loc", "script_noteworthy" );
    var_2 = undefined;
    var_3 = 10;
    var_4 = 1;

    while ( isdefined( var_0 ) && _id_0547::_id_5565( var_0.sgboss, 1 ) )
    {
        if ( var_1.size == 0 )
        {
            _id_0547::_id_A6F6();
            continue;
        }

        var_5 = common_scripts\utility::_id_4461( var_0.origin, var_1 );

        if ( isdefined( var_2 ) )
        {
            while ( var_2 == var_5 )
            {
                var_6 = common_scripts\utility::_id_0F93( var_1, var_5 );
                var_5 = common_scripts\utility::_id_4461( var_0.origin, var_6 );
                waitframe();
            }
        }

        var_7 = spawn( "script_model", var_5.origin );
        var_7 setmodel( "tag_origin" );
        var_7 thread drop_bombs_fx( var_3 );
        var_5 thread drop_bombs_damage( var_3 );
        var_2 = var_5;
        level.zmb_windmill_num_airstrikes++;
        wait( var_3 + var_4 );
    }
}

drop_bombs_fx( var_0 )
{
    var_1 = _func_2A8( common_scripts\utility::_id_44F5( "bombing_run_targeting" ), self, "tag_origin" );
    _func_14C( var_1 );
    _id_0378::_id_8D74( "drop_bombs_fall", self, var_0 );
    wait( var_0 );
    playfx( level._effect["bombing_run_bomb_explode"], self.origin );
    _id_0378::_id_8D74( "drop_bombs_explosion", self );
    var_1 delete();
    self delete();
}

drop_bombs_damage( var_0 )
{
    var_1 = self;
    wait( var_0 );
    var_2 = _id_0547::_id_408F();
    var_3 = _func_1AC( var_2, self.origin, 400 );
    var_4 = _func_1AC( level.players, self.origin, 350 );

    foreach ( var_6 in var_3 )
    {
        if ( isdefined( var_6._id_0A4B ) && var_6._id_0A4B != "zombie_fireman" )
            var_6 _meth_8059( var_6.health + 666, var_1.origin );

        if ( _id_0547::_id_5565( var_6._id_0A4B, "zombie_fireman" ) )
            var_6 notify( "break_shield_now" );
    }

    foreach ( var_9 in var_4 )
        var_9 _meth_8059( self.health + 30, var_1.origin );

    level thread pause_wave_for_a_moment();
}

pause_wave_for_a_moment()
{
    level notify( "new_pause_wave_for_a_moment" );
    level endon( "new_pause_wave_for_a_moment" );
    level endon( "zmb_shotgun_gamemode_pausing" );
    level endon( "fireman_boss_has_died" );

    if ( common_scripts\utility::_id_562E( level.fireman_boss_has_died ) )
        return;

    maps\mp\mp_zombie_nest_ee_wave_manipulation::_id_8608();
    wait 8;
    maps\mp\mp_zombie_nest_ee_wave_manipulation::_id_8607();
}

______silly_fun_functions_________()
{

}

intro_special_zombies_init()
{
    _id_0547::_id_7BA9( ::special_decorator_zombie_killed );
    var_0 = 0;

    for (;;)
    {
        level waittill( "zombie_spawned", var_1 );

        if ( !isdefined( var_1._id_0A4B ) )
            continue;

        if ( var_1._id_0A4B == "zombie_generic" )
        {
            var_2 = _func_0A4( 0, 18 );

            if ( var_2 <= 1 && !common_scripts\utility::_id_562E( self.hasprop ) && var_0 < level.max_prop_zombie_appearances )
            {
                var_0++;
                var_1 thread intro_special_zombies_attach();
                wait 600;
            }
        }
    }
}

intro_special_zombies_attach()
{
    self.hasprop = 1;
    self.prop_decorator = spawn( "script_model", self.origin );

    if ( self._id_4B6E == 0 && self._id_4B5A == 0 )
        var_0 = _func_0A4( 2, 4 );
    else
        var_0 = _func_0A4( 0, 2 );

    switch ( var_0 )
    {
        case 0:
            self.prop_decorator setmodel( "hur_broom_straw_01" );
            self.prop_decorator _meth_8055( self, "J_SpineLower", ( 4, 0, -28 ), ( 0, 0, 0 ) );
            break;
        case 1:
            self.prop_decorator setmodel( "dun_broom_02" );
            self.prop_decorator _meth_8055( self, "J_SpineLower", ( 4, 0, -28 ), ( 0, 0, 0 ) );
            break;
        case 2:
            self.prop_decorator setmodel( "aac_kitchen_skillet_01" );
            self.prop_decorator _meth_8055( self, "J_Head", ( 7.25, 0, 0 ), ( 0, 90, -90 ) );
            break;
        case 3:
            self.prop_decorator setmodel( "usa_water_bucket_01" );
            self.prop_decorator _meth_8055( self, "J_Head", ( 8.5, 0, 0 ), ( 0, 90, -90 ) );
            break;
        default:
            break;
    }

    self.prop_decorator _meth_82C2();
}

special_decorator_zombie_killed( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    if ( isdefined( self.prop_decorator ) )
        self.prop_decorator delete();
}

________objective_functions_________()
{

}

objective_extermination_bomber_movemode()
{
    return _id_054D::_id_957E( 100 );
}

objective_zeppelin_launcher_zombie()
{
    _id_0547::_id_7BA9( ::objective_zeppelin_launcher_zombie_killed );

    for (;;)
    {
        level waittill( "zombie_spawned", var_0 );

        if ( var_0._id_0A4B == "zombie_generic" )
        {
            var_1 = _func_0A4( 0, 18 );

            if ( var_1 <= 1 && !common_scripts\utility::_id_562E( self.haslauncher ) )
                var_0 thread objective_zeppelin_launcher_zombie_attach();
        }
    }
}

objective_zeppelin_launcher_zombie_attach()
{
    self.haslauncher = 1;
    self attach( "ger_m_valbag_r1c1" );
    self.launcher_mdl = spawn( "script_model", self.origin );
    self.launcher_mdl setmodel( "npc_ger_panzerschreck_base" );
    self.launcher_mdl _meth_8055( self, "J_SpineUpper", ( 5, 8, 5 ), ( 0, 0, 0 ) );
    self.launcher_mdl _meth_82C2();
}

objective_zeppelin_launcher_zombie_killed( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    if ( isdefined( self.launcher_mdl ) )
        self.launcher_mdl delete();

    if ( !isdefined( var_0 ) || !isplayer( var_0 ) )
        return;

    if ( isdefined( self.haslauncher ) && self.haslauncher == 1 )
    {
        if ( _id_0547::_id_5864( var_4 ) || _id_0547::_id_5752( var_4 ) )
            level thread objective_zeppelin_launcher_switchto( var_0 );
    }
}

objective_zeppelin_launcher_switchto( var_0 )
{
    var_1 = var_0 _meth_8317();
    var_2 = "panzerschreck_zm";
    var_0 giveweapon( var_2 );
    var_0 switchtoweapon( var_2 );

    while ( var_0 getammocount( var_2 ) > 0 )
        waitframe();

    var_0 takeweapon( var_2 );
}

________objective_success_and_fail_functions_________()
{

}

objective_escort_success()
{
    level thread common_scripts\_exploder::_id_088E( 201 );
    wait 0.15;
    var_0 = getentarray( "escort_barricade", "targetname" );
    _id_0378::_id_8D74( "bomber_barricade_explosion", var_0 );

    foreach ( var_2 in var_0 )
    {
        if ( isdefined( var_2 ) )
            var_2 delete();
    }
}

performance_stuff()
{
    setdvar( "634", 0 );
    setdvar( "4042", 0 );
    setdvar( "5153", 0 );
    setdvar( "3220", 0.5 );
}
