// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_9CAA( var_0 )
{
    level notify( "firewell_machinery_reset" );
    wait 1.5;
    maps\mp\mp_zombie_nest_ee_fire_well::_id_9CAB( var_0 );
}
