// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

#using_animtree("zombie_guardian");

init()
{
    level._effect["zmb_guardian_club_gk_l"] = loadfx( "vfx/zombie/zmb_guardian_club_gk_l" );
    level._effect["zmb_guardian_club_gk_r"] = loadfx( "vfx/zombie/zmb_guardian_club_gk_r" );
    level._effect["zmb_guardian_eyes_gk"] = loadfx( "vfx/zombie/zmb_guardian_eyes_gk" );
    level._effect["zmb_guardian_feast_drain"] = loadfx( "vfx/zombie/zmb_guardian_zmb_feast" );
    level._effect["zmb_guardian_feast_drain_death"] = loadfx( "vfx/zombie/zmb_guardian_zmb_feast_death" );
    level._effect["dlc_zmb_dig02_blood_plates_emis"] = loadfx( "vfx/map/mp_zombie_dig02/dlc_zmb_dig02_blood_plates_emis" );
    level._effect["dlc_zmb_dig02_boss_shield"] = loadfx( "vfx/map/mp_zombie_dig02/dlc_zmb_dig02_boss_shield" );
    level._effect["dlc_zmb_dig02_boss_shield_burst"] = loadfx( "vfx/map/mp_zombie_dig02/dlc_zmb_dig02_boss_shield_burst" );
    level._effect["dlc_zmb_dig02_pulse_radius_250"] = loadfx( "vfx/map/mp_zombie_dig02/dlc_zmb_dig02_pulse_radius_250" );
    level._effect["zmb_guardian_gk_impact"] = loadfx( "vfx/zombie/zmb_guardian_gk_impact" );
    level._effect["dlc_zmb_dig02_pulse_shock"] = loadfx( "vfx/zombie/zmb_giestkraft_impact" );
    level._effect["dlc_zmb_dig02_statue_gk_shield"] = loadfx( "vfx/map/mp_zombie_dig02/dlc_zmb_dig02_statue_gk_shield" );
    level._effect["zmb_hilt_sphere_explosion"] = loadfx( "vfx/explosion/zmb_hilt_sphere_explosion" );
    level._effect["zmb_guardian_feast_radius_256_rnr"] = loadfx( "vfx/zombie/zmb_guardian_feast_radius_256_rnr" );
    maps\mp\agents\_scripted_agent_anim_util::_id_5159( "zombie_guardian" );
    level._id_0A41["zombie_guardian"] = level._id_0A41["zombie"];
    level._id_0A41["zombie_guardian"]["think"] = ::guardian_think;
    level._id_0A41["zombie_guardian"]["move_mode"] = ::guardian_move_mode_func;
    level._id_0A41["zombie_guardian"]["on_damaged_finished"] = ::guardian_on_damaged_finished;
    level._id_0A41["zombie_guardian"]["on_damaged"] = ::guardian_on_damaged;
    level._id_0A41["zombie_guardian"]["post_model"] = ::guardian_post_model;
    level._id_0A41["zombie_guardian"]["tesla_delayed_dmg"] = ::guardian_tesla_delayed_dmg;
    var_0 = spawnstruct();
    var_0._id_0A4B = "zombie_guardian";
    var_0._id_0EAE = "zombie_guardian_animclass";
    var_0._id_0E88 = "zombie_guardian";
    var_0._id_0879 = "zombie_guardian";
    var_0._id_4C12 = 10;
    var_0.overridehealth = int( guardian_health_scale() * 175000 );
    var_0._id_60E2 = 65;
    var_0._id_8302 = 100;
    var_0._id_8303 = 32;
    var_0.parenttype = "zombie_generic";
    var_0.tacklebymelee = 0;
    var_0.tacklebycharge = 0;
    var_0.knockbyravensword = 0;
    var_0.shockbyteslablood = 0;
    var_0.scaleshealthbyplayers = 1;
    var_0.bombsabotagefunc = ::bomb_sabotage_func;
    level.guardian_plate_damage_limit = 3000;
    var_0._id_5ED2["zombie_guardian"]["whole_body"] = "zom_guardian_base";
    _id_0547::_id_0A52( var_0, "zombie_guardian" );
    _id_0547::registeranimtree( "zombie_guardian", #animtree );
    _id_0541::_id_2F92( "crawl", [ "zombie_guardian" ] );
    guardian_init_phase_handler();
    _id_0547::_id_7BD0( "grd_enter_drain", ::guardian_state_seek_drain, undefined, 7, ::guardian_state_seek_drain_cleanup );
    _id_0547::_id_7BD0( "grd_drain", ::guardian_state_drain, ::guardian_state_drain_cleanup, 6, ::guardian_state_drain_cleanup );
    _id_0547::_id_7BD0( "grd_drain_knockback", ::guardian_state_drain_knockback, ::guardian_state_drain_knockback_cleanup, 6, ::guardian_state_drain_knockback_cleanup );
    _id_0547::_id_7BD0( "grd_pulse", ::guardian_state_pulse, ::guardian_state_pulse_interrupt, 6, ::guardian_state_pulse_cleanup );
    _id_0547::_id_7BD0( "grd_feast", ::guardian_state_feast, ::guardian_state_feast_interrupt, 6, ::guardian_state_feast_cleanup );
}

_________difficulty__________()
{

}

init_guardian_diff_settings()
{
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::add_difficulty_setting( "Guardian Base Health", "guardian_health_scale", [ 175000, 306250.0, 437500.0, 481250.0 ] );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::add_difficulty_setting( "Guardian Geist Max", "guardian_geist_max", [ 70000, 122500.0, 175000.0, 192500.0 ] );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::add_difficulty_setting( "Guardian Damage Debuff", "guardian_damage_debuff", [ 0.6, 0.5, 0.4, 0.4 ] );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::add_difficulty_setting( "Guardian Plate Health", "guardian_plate_health", [ 3000, 6000, 9000, 12000 ] );
    maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::add_difficulty_setting( "Guardian Feast Health Regen", "guardian_feast_health_regen", [ 500, 1000, 1500, 2000 ] );
}

init_guardian_health()
{
    var_0 = guardian_health_scale();
    var_1 = int( var_0 * 175000 );

    if ( isdefined( level.zmb_sg_difficulty_settings ) )
    {
        var_2 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "guardian_health_scale" );

        if ( isdefined( var_2 ) )
            var_1 = var_2;
    }

    maps\mp\agents\_agent_common::_id_83FD( var_1 );
    var_3 = _id_0547::_id_0A51( self._id_0A4B );
    var_3.overridehealth = var_1;
}

init_guardian_scalars()
{
    var_0 = guardian_health_scale();
    var_1 = 70000 * var_0;
    var_2 = 1;
    var_3 = 0.5;

    if ( isdefined( level.zmb_sg_difficulty_settings ) )
    {
        var_4 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "guardian_geist_max" );
        var_5 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "guardian_plate_health" );
        var_6 = maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "guardian_damage_debuff" );

        if ( isdefined( var_4 ) )
            var_1 = var_4;

        if ( isdefined( var_5 ) )
            level.guardian_plate_damage_limit = var_5;

        if ( isdefined( var_6 ) )
            var_2 = var_6;
    }

    self.geist_max = var_1;
    self.geist_current = self.geist_max;
    self.dmg_debuff = var_2;
    self.geist_dmg_debuff = var_3;
}

guardian_health_thresholds_calc()
{
    waitframe();
    self.stage1health = int( self.health * 0.75 );
    self.stage2health = int( self.health * 0.5 );
    self.stage3health = int( self.health * 0.25 );
    self.current_drain_threshold = self.stage1health;
}

guardian_health_scale()
{
    var_0 = 1.0;

    switch ( level.players.size )
    {
        case 1:
            var_0 = 1.0;
            break;
        case 2:
            var_0 = 1.75;
            break;
        case 3:
            var_0 = 2.5;
            break;
        case 4:
            var_0 = 2.75;
            break;
        default:
            var_0 = 1.0;
            break;
    }

    return var_0;
}

guardian_think_setup()
{
    self _meth_85A1( "zombie_guardian" );
    common_scripts\utility::_id_3799( "grd_basic" );
    common_scripts\utility::_id_3799( "grd_downed" );
    common_scripts\utility::_id_3799( "grd_enraged" );
    init_guardian_health();
    init_guardian_scalars();
    self.stage1health = 0;
    self.stage2health = 0;
    self.stage3health = 0;
    self.current_drain_threshold = 0;
    thread guardian_club_gk_vfx_on();
    thread guardian_footstep_quake_handler();
    _id_0566::_id_ABB5();
    self._id_55AB = 1;
    self._id_57E8 = 1;
    self._id_562B = 1;
    self.isteslastunimmune = 1;
    self.is_flamethrower_resistent = 1;
    self.ignoredistractiondrones = 1;
    self.shortstun = 1;
    self.grd_pulse_cooldown_time_max = 20;
    self.grd_pulse_cooldown_time_min = 15;
    self.plate_drain_cooldown_time_min = 15;
    self.plate_drain_cooldown_time_max = 20;
    self.zmdemigod = 1;
    self.zombie_guardian_can_take_damage = 1;
    self.zombie_guardian_can_take_geist_damage = 1;
    self._id_6816 = 1;
    self.nomutilate = 1;
    self.nopairmelee = 1;
    self._id_66EC = 1;
    self._id_15E1 = 1;
    self.shield_active = 1;
    self._id_00BD = 100;
    self.radius = 32;
    self._id_2BCA = self.radius + 1;
    self _meth_8399( self._id_2BCA );
    _id_0547::_id_86C8( 115 );
    _id_0547::_id_86C7( 115 );
    self.candamageallies = 1;
    self._id_11AB = 85 + self.radius;
    self._id_60F5 = "large";
    self._id_60F6 = 200;
    self._id_60E1 = 40;
    self.customrecyclehandling = ::guardian_recycle_handling;
    self.knockdowntime = 4;
    self _meth_84D4();
    guardian_set_phase( "grd_basic" );
    level.num_orbs = 1;

    if ( level.players.size > 2 )
        level.num_orbs = 2;
}

guardian_post_model()
{
    foreach ( var_1 in [ "j_wrist_ri", "j_wrist_le" ] )
        thread guardian_tackle_thread( var_1 );
}

guardian_recycle_handling()
{
    var_0 = common_scripts\utility::_id_46B5( "sg_boss_spawnpoint", "targetname" );

    if ( isdefined( var_0 ) )
        self.origin = var_0.origin;
}

guardian_tesla_delayed_dmg( var_0, var_1, var_2 )
{
    return var_0;
}

guardian_footstep_quake_handler()
{
    self endon( "death" );

    for (;;)
    {
        [var_1, var_2] = common_scripts\utility::_id_A717( "move_loop", "move_start", "move_stop", "turn_in_place", "attack_anim" );

        if ( issubstr( var_2, "footstep" ) )
            _func_17F( 0.1, 0.1, self.origin, 512 );
    }
}

guardian_geist_monitor()
{
    self endon( "death" );
    self.last_enraged_time = undefined;
    var_0 = 20;

    for (;;)
    {
        if ( self.geist_current < self.geist_ravenous_threshold && !common_scripts\utility::_id_3794( "grd_enraged" ) )
        {
            common_scripts\utility::_id_379A( "grd_enraged" );
            self.last_enraged_time = gettime();
            self.zombie_guardian_can_take_geist_damage = 0;
        }
        else if ( common_scripts\utility::_id_3794( "grd_enraged" ) && gettime() > self.last_enraged_time + var_0 * 1000 )
        {
            common_scripts\utility::_id_3796( "grd_enraged" );
            self.geist_current = self.geist_max;
            self.zombie_guardian_can_take_geist_damage = 1;
        }

        waitframe();
    }
}

guardian_force_enrage()
{
    common_scripts\utility::_id_379A( "grd_enraged" );
    self.last_enraged_time = gettime();
    self.zombie_guardian_can_take_geist_damage = 0;
}

_________tackle__________()
{

}

guardian_tackle_thread( var_0 )
{
    var_1 = self;
    var_1 endon( "death" );
    var_2 = var_1 _meth_8445( var_0 );

    if ( var_2 == -1 )
        return;

    var_3 = spawnstruct();
    var_3.origin = var_1 gettagorigin( var_0 );
    var_3.angles = var_1.angles;
    var_3._id_2F74 = 0;
    var_4 = spawnstruct();
    var_4._id_2434 = 20;
    var_4._id_60C1 = 50;
    var_4._id_3A20 = 80;
    var_4._id_1B70 = 72;
    var_1 childthread _id_0547::tackle_thread( var_3, var_4 );

    for (;;)
    {
        wait 0.1;
        var_3.origin = var_1 gettagorigin( var_0 );
        var_3.angles = var_1.angles;
        var_3._id_2F74 = common_scripts\utility::_id_562E( var_1.is_pulsing ) || common_scripts\utility::_id_562E( var_1.is_feasting ) || common_scripts\utility::_id_562E( var_1.is_draining );
    }
}

guardian_tackle_lethal()
{
    self endon( "death" );
    level endon( "game_ended" );
    var_0 = _func_0DA( 50 );

    for (;;)
    {
        waitframe();
        var_1 = anglestoforward( self.angles * ( 0, 1, 0 ) );
        var_2 = length( self _meth_833D() );

        if ( var_2 < 50 )
            continue;

        foreach ( var_4 in level._id_0A4E )
        {
            if ( !isdefined( var_4 ) || !isalive( var_4 ) || var_4 == self || isdefined( var_4.team ) && _func_100( self.team, var_4.team ) )
                continue;

            if ( _id_0547::_id_5565( var_4._id_0A4B, "zombie_heavy" ) )
                continue;

            if ( distancesquared( self.origin, var_4.origin ) > var_0 )
                continue;

            var_5 = ( var_4.origin - self.origin ) * ( 1, 1, 0 );

            if ( vectordot( var_5, var_1 ) < 0 )
                continue;

            var_5 = vectornormalize( var_5 );
            guardian_tackle_lethal_agent( var_4, var_5 );
        }
    }
}

guardian_tackle_lethal_agent( var_0, var_1 )
{
    if ( _func_0A3( 1 ) < 0.5 )
        guardian_tackle_lethal_ragdoll( var_0, var_1, 1, 2 );
    else
        guardian_tackle_lethal_ragdoll( var_0, var_1, 2, 3 );
}

guardian_tackle_lethal_ragdoll( var_0, var_1, var_2, var_3 )
{
    var_0._id_78D2 = 1;
    var_0 _meth_8059( var_0.health + 666, self.origin, undefined, undefined, "MOD_EXPLOSIVE" );
    var_4 = self.origin - var_1 + ( 0, 0, 8 );
    wait 0.1;
    var_5 = _func_0A5( var_2, var_3 );
    _func_175( var_4, 128, 0, var_5, 0 );
}

_________think__________()
{

}

guardian_think()
{
    self endon( "death" );
    level endon( "game_ended" );
    self endon( "owner_disconnect" );
    guardian_think_setup();
    thread guardian_think_stages();
    thread guardian_tackle_lethal();

    for (;;)
    {
        wait 0.2;

        if ( common_scripts\utility::_id_3794( "grd_downed" ) )
            continue;

        guardian_run_phase_logic();

        if ( common_scripts\utility::_id_562E( self._id_57C0 ) )
            continue;

        if ( _id_053C::_id_4F84() )
            continue;

        if ( _id_053C::_id_4F9B() )
            continue;

        if ( _id_053C::_id_4F9A() )
            continue;

        _id_053C::_id_0647();
    }
}

guardian_think_stages()
{
    self endon( "death" );
    thread guardian_think_drain_monitor();
    thread guardian_think_orb_monitor();

    while ( self.health > 1 )
        wait 0.5;

    self.sgboss = 0;
    self.sgisdyingboss = 1;
    self.zmdemigod = 0;
    guardian_set_damage_limited( 0 );
    var_0 = length( self _meth_833D() );

    if ( var_0 < 50 )
        self._id_2A9D = "death_full_body_stand";
    else
        self._id_2A9D = "death_sprint";

    self _meth_8059( 1, ( 0, 0, 0 ), undefined, undefined, undefined, "m1911_zm" );
}

guardian_think_orb_monitor()
{
    self endon( "death" );

    while ( self.health > self.stage2health )
        wait 0.5;

    thread guardian_think_stages_increase_orb_req();

    while ( self.health > self.stage3health )
        wait 0.5;

    thread guardian_think_stages_increase_orb_req();
}

guardian_think_drain_monitor()
{
    self endon( "death" );
    self.current_drain_threshold = self.stage1health;

    for (;;)
    {
        wait 0.5;

        if ( self.num_drain_attempts <= 0 )
        {
            self.current_drain_threshold = self.stage1health;
            continue;
        }
        else if ( self.num_drain_attempts > 0 && self.num_drain_attempts < 2 )
        {
            self.current_drain_threshold = self.stage2health;
            continue;
        }
        else if ( self.num_drain_attempts >= 2 && self.num_drain_attempts < 4 )
        {
            self.current_drain_threshold = self.stage3health;
            continue;
        }
        else if ( self.num_drain_attempts >= 4 && !common_scripts\utility::_id_562E( level.zmb_red_skull_mode_activated ) )
        {
            self.current_drain_threshold = self.maxhealth * 0.05;
            continue;
        }
    }
}

guardian_think_stages_increase_orb_req()
{
    while ( common_scripts\utility::_id_562E( self.is_draining ) || common_scripts\utility::_id_562E( self.is_seeking_drain_point ) )
        wait 0.5;

    level.num_orbs++;

    if ( level.players.size <= 2 && level.num_orbs > 3 )
        level.num_orbs = 3;
}

guardian_think_basic()
{
    self endon( "death" );

    if ( maps\mp\agents\_scripted_agent_anim_util::_id_57E2() )
        return 0;

    if ( isdefined( self.enterednewphase ) )
    {
        self.is_feasting = 0;
        self.is_pulsing = 0;
        self.is_seeking_drain_point = 0;
        self.is_draining = 0;
        self.drain_queued = 0;
        self.enterednewphase = undefined;

        if ( !isdefined( self.num_drain_attempts_failed ) )
            self.num_drain_attempts_failed = 0;

        if ( !isdefined( self.num_drain_attempts ) )
            self.num_drain_attempts = 0;

        if ( !common_scripts\utility::_id_562E( self.firstrun ) )
        {
            self.firstrun = 1;
            maps\mp\_utility::_id_2CED( 5, ::special_set_paused, 0 );
        }
        else
            special_set_paused( 0 );
    }

    if ( common_scripts\utility::_id_562E( self.is_pulsing ) || common_scripts\utility::_id_562E( self.is_draining ) || common_scripts\utility::_id_562E( self.is_feasting ) || common_scripts\utility::_id_562E( self.is_seeking_drain_point ) )
    {
        if ( special_can_perform() )
            special_schedule_next();

        return 0;
    }

    if ( common_scripts\utility::_id_562E( self.drain_queued ) )
    {
        var_0 = 1;

        if ( var_0 )
        {
            self.is_seeking_drain_point = 1;
            special_set_paused( 1 );
            thread plate_drain_logic();
        }

        return 0;
    }

    if ( special_can_perform() )
    {
        special_attempt();
        return 0;
    }

    return 0;
}

guardian_move_mode_func()
{
    if ( common_scripts\utility::_id_562E( self.is_seeking_drain_point ) )
    {
        self._id_64C2 = 1.0 * _id_054D::_id_4440();
        return "sprint";
    }

    if ( common_scripts\utility::_id_3794( "grd_enraged" ) )
    {
        self._id_64C2 = 0.9 * _id_054D::_id_4440();
        return "sprint";
    }

    return "run";
}

_________damage__________()
{

}

guardian_on_damaged( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 )
{
    var_11 = var_2;
    self.lastweapondamage = var_5;
    self._id_00E6 = var_1;

    if ( isdefined( level.zmb_boss_damage_reduction_func ) )
        var_2 = [[ level.zmb_boss_damage_reduction_func ]]( var_5, var_2 );

    if ( common_scripts\utility::_id_3794( "grd_downed" ) )
        return;

    if ( !isdefined( var_1 ) || isdefined( var_1 ) && !isplayer( var_1 ) )
        return;

    if ( common_scripts\utility::_id_562E( self.is_draining ) && !common_scripts\utility::_id_562E( level.nodamagescalingweapons[var_5] ) )
        return;

    if ( common_scripts\utility::_id_562E( self.zombie_guardian_can_take_geist_damage ) )
    {
        var_12 = var_2;

        if ( isdefined( var_4 ) && ( var_4 == "MOD_EXPLOSIVE_BULLET" || var_4 == "MOD_EXPLOSIVE" ) )
            var_12 = int( var_2 * self.geist_dmg_debuff );

        if ( var_12 > 1000 )
            var_12 = 1000;

        if ( isdefined( var_5 ) && issubstr( var_5, "zom_dlc3_5" ) )
            var_12 = 500;

        if ( self.geist_current - var_12 > 0 )
            self.geist_current = self.geist_current - var_12;
    }

    if ( common_scripts\utility::_id_562E( self.shield_active ) )
    {
        if ( _id_0547::_id_5565( var_8, "right_hand" ) || _id_0547::_id_5565( var_8, "left_hand" ) )
            var_2 = int( var_2 * 1.25 );

        if ( isdefined( var_5 ) && issubstr( var_5, "zom_dlc3_5" ) )
            var_2 = max( var_2, int( self.maxhealth * 0.01 ) );

        if ( var_2 > 1 )
            var_2 = int( var_2 * self.dmg_debuff );

        if ( var_2 > self.maxhealth * 0.015 && isdefined( var_5 ) && issubstr( var_5, "zom_dlc3_5" ) )
            var_2 = int( self.maxhealth * 0.015 );

        _func_147( level._effect["zmb_guardian_gk_impact"], self, "J_Spine4" );
    }
    else if ( isdefined( var_5 ) && issubstr( var_5, "zom_dlc3_5" ) )
    {
        var_13 = 0.02;

        if ( common_scripts\utility::_id_562E( level.zmb_red_skull_mode_activated ) && level.players.size <= 1 )
            var_13 = 0.022;

        var_2 = max( var_2, int( self.maxhealth * var_13 ) );
    }
    else
        var_2 = int( var_2 * 1.5 );

    if ( common_scripts\utility::_id_562E( level.nodamagescalingweapons[var_5] ) )
        var_2 = var_11;

    _id_054D::_id_6BD1( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 );
}

guardian_check_if_weapon_op( var_0, var_1 )
{
    var_2 = 0;

    if ( !isdefined( var_0 ) )
        return 0;

    if ( issubstr( var_0, "p38_" ) && issubstr( var_0, "_pap_zm" ) )
        var_2 = 1;

    if ( _id_0547::_id_5565( var_1, "MOD_EXPLOSIVE" ) || _id_0547::_id_5565( var_1, "MOD_EXPLOSIVE_BULLET" ) )
        var_2 = 1;

    return var_2;
}

guardian_on_damaged_finished( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 )
{
    if ( isdefined( var_5 ) && isdefined( var_4 ) )
    {
        if ( guardian_check_if_weapon_op( var_5, var_4 ) && var_2 > 1 )
            var_2 = int( var_2 * 0.75 );
    }

    if ( isdefined( self.zombie_limit_damage ) && !( isdefined( var_5 ) && issubstr( var_5, "zom_dlc3_5" ) ) )
    {
        self.zombie_limit_damage = self.zombie_limit_damage - var_2;

        if ( self.zombie_limit_damage < 0 )
        {
            self.zombie_guardian_can_take_damage = 0;
            var_2 = var_2 + self.zombie_limit_damage;
            self.zombie_limit_damage = 0;
        }
    }

    if ( isdefined( var_1 ) && isplayer( var_1 ) )
    {
        var_11 = "minor";

        if ( common_scripts\utility::_id_562E( self.shield_active ) || !self.zombie_guardian_can_take_damage )
            var_11 = "minor";
        else
            var_11 = "weakpoint";

        var_1 thread _id_04C7::_id_A102( var_11 );
    }

    if ( var_2 == 0 )
        return;

    if ( !self.zombie_guardian_can_take_damage && !common_scripts\utility::_id_562E( level.nodamagescalingweapons[var_5] ) )
        return;

    if ( self.health - var_2 < self.current_drain_threshold && self.health - var_2 > 0 )
    {
        if ( !common_scripts\utility::_id_562E( self.drain_queued ) && !common_scripts\utility::_id_562E( self.is_pulsing ) && !common_scripts\utility::_id_562E( self.is_draining ) && !common_scripts\utility::_id_562E( self.is_feasting ) && !common_scripts\utility::_id_562E( self.is_seeking_drain_point ) )
        {
            if ( plate_drain_can_drain() )
                self.drain_queued = 1;
        }
    }

    _id_054D::_id_6BD3( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 );
}

guardian_init_phase_handler()
{
    var_0 = spawnstruct();
    var_0._id_3F02 = _id_0547::_id_4B2C;
    var_0.value = 0;
    guardian_register_phase( "grd_basic", "grd_basic", ::guardian_think_basic, [], [ "grd_downed" ], [ var_0 ] );
}

guardian_register_phase( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    if ( !isdefined( level.zmb_grd_agent_phases ) )
        level.zmb_grd_agent_phases = [];

    var_6 = spawnstruct();
    var_6.name = var_0;
    var_6.next_phase = var_1;
    var_6.func_and_data = common_scripts\utility::_id_0F73( [ var_2 ], var_3 );
    var_6.reasons_to_skip = var_4;
    var_6.reasons_to_block_progress = var_5;
    level.zmb_grd_agent_phases[var_6.name] = var_6;
}

guardian_set_phase( var_0 )
{
    foreach ( var_2 in level.zmb_grd_agent_phases )
        common_scripts\utility::_id_3796( var_2.name );

    common_scripts\utility::_id_379A( var_0 );
    self.enterednewphase = 1;
}

guardian_has_excuse_to_skip( var_0 )
{
    if ( !isdefined( var_0.reasons_to_skip ) )
        return 0;

    foreach ( var_2 in var_0.reasons_to_skip )
    {
        if ( common_scripts\utility::_id_3794( var_2 ) )
            return 1;
    }

    return 0;
}

guardian_run_phase_logic()
{
    foreach ( var_1 in level.zmb_grd_agent_phases )
    {
        if ( common_scripts\utility::_id_3794( var_1.name ) )
            guardian_phase_handler( var_1 );
    }
}

guardian_phase_handler( var_0 )
{
    var_1 = guardian_has_excuse_to_skip( var_0 );

    if ( !var_1 )
    {
        foreach ( var_3 in var_0.reasons_to_block_progress )
        {
            if ( self [[ var_3._id_3F02 ]]() == var_3.value )
                return;
        }

        var_1 = common_scripts\utility::_id_8134( var_0.func_and_data );
    }

    if ( var_1 )
        guardian_set_phase( var_0.next_phase );
}

_________action_general__________()
{

}

special_attempt()
{
    waitframe();
    var_0 = 0;
    var_1 = 0;

    if ( self.health <= self.maxhealth * 0.25 )
        var_1 = 1;

    if ( common_scripts\utility::_id_3794( "grd_enraged" ) && !common_scripts\utility::_id_562E( var_1 ) )
    {
        var_2 = common_scripts\utility::_id_4461( self.origin, level.players, 256 );

        if ( isdefined( var_2 ) )
            var_1 = 1;

        if ( !common_scripts\utility::_id_562E( var_1 ) )
            var_1 = common_scripts\utility::_id_24A6();
    }

    foreach ( var_4 in level.players )
    {
        if ( pulse_can_hit_player( var_4 ) )
        {
            var_0 = 1;
            break;
        }
    }

    if ( var_1 && var_0 )
    {
        if ( common_scripts\utility::_id_24A6() )
            thread pulse_perform();
        else
            thread feast_perform();
    }
    else if ( var_1 )
        thread feast_perform();
    else if ( var_0 )
        thread pulse_perform();
}

special_can_perform()
{
    return isdefined( self.next_special_time ) && gettime() >= self.next_special_time;
}

special_set_paused( var_0 )
{
    if ( !isdefined( self.next_special_time ) )
        self.next_special_time = undefined;

    if ( common_scripts\utility::_id_562E( var_0 ) )
        self.next_special_time = undefined;
    else
        special_schedule_next();
}

special_schedule_next()
{
    var_0 = _func_0A4( self.grd_pulse_cooldown_time_min, self.grd_pulse_cooldown_time_max );

    if ( common_scripts\utility::_id_3794( "grd_enraged" ) )
        self.next_special_time = gettime() + var_0 * 0.5 * 1000;
    else
        self.next_special_time = gettime() + var_0 * 1000;
}

_________action_feast__________()
{

}

guardian_state_feast()
{
    self endon( "death" );
    var_0 = "scripted_grd_stand_to_crouch_fast";
    var_1 = "crouch_consume";
    var_2 = "crouch_consume_2_stand";
    var_3 = self [[ maps\mp\agents\_agent_utility::_id_0A59( "get_action_params" ) ]]();
    var_4 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_0, var_3 );
    var_5 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_1, var_3 );
    var_6 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_2, var_3 );
    var_7 = self _meth_83DB( var_4 );
    thread feast_notetrack_handler();
    thread feast_attract_zombies();

    if ( isdefined( var_7 ) && var_7 > 0 )
    {
        guardian_set_damage_limited( 1 );
        self _meth_83A2( 1 );
        maps\mp\agents\_scripted_agent_anim_util::_id_8732( 1, "ScriptedAnimation" );
        self _meth_839C( "anim deltas" );
        self _meth_839B( "face angle abs", self.angles );
        self _meth_839A( 1, 1 );
        self _meth_839D( "gravity" );
        maps\mp\agents\_scripted_agent_anim_util::_id_71FD( var_4, 0, "scripted_anim" );
        maps\mp\agents\_scripted_agent_anim_util::_id_8415( var_5, 0 );
        var_8 = feast_wait_for_timeout_or_sated();
        maps\mp\agents\_scripted_agent_anim_util::_id_71FD( var_6, 0, "scripted_anim" );
        maps\mp\agents\_scripted_agent_anim_util::_id_8732( 0, "ScriptedAnimation" );
        self _meth_83A2( 0 );
        self _meth_839D( "gravity" );
    }
}

guardian_state_feast_interrupt()
{
    guardian_state_feast_cleanup();
}

guardian_state_feast_cleanup()
{
    self.is_feasting = 0;
    guardian_set_damage_limited( 0 );
    special_schedule_next();
}

feast_perform()
{
    self endon( "death" );

    if ( common_scripts\utility::_id_562E( self.is_pulsing ) || common_scripts\utility::_id_562E( self.is_feasting ) )
    {
        special_schedule_next();
        return;
    }

    self.is_feasting = 1;
    _id_0547::_id_7D1A( "grd_feast", undefined, 0.5 );
}

feast_wait_for_timeout_or_sated()
{
    self endon( "death" );
    self.feast_kill_count = 0;
    self.feast_player_kill_count = 0;
    var_0 = gettime();
    var_1 = 10;
    var_2 = "timeout";

    for (;;)
    {
        if ( ( gettime() - var_0 ) / 1000 >= var_1 )
        {
            var_2 = "timeout";
            break;
        }

        if ( self.feast_player_kill_count >= 1 )
        {
            var_2 = "sated";
            break;
        }

        waitframe();
    }

    self.feast_kill_count = 0;
    self.feast_player_kill_count = 0;
    self notify( "guardian_feast_stop", var_2 );
    return var_2;
}

feast_notetrack_handler()
{
    self endon( "death" );
    self endon( "guardian_feast_stop" );
    var_0 = gettime();
    var_1 = undefined;
    var_2 = undefined;
    var_3 = "s2_grd_crouch_consume";
    var_4 = "idle_anim";
    var_5 = "dmg_slam_down";

    for (;;)
    {
        self waittill( var_4, var_6 );

        if ( var_6 == var_5 || var_6 == "end" || var_6 == "anim_will_finish" || var_6 == "finish" )
        {
            level notify( "guardian_pound_ping" );
            thread feast_smash_close_zombies();
            thread feast_smash_close_players();
        }
    }
}

feast_smash_close_zombies()
{
    var_0 = _id_0547::_id_408F();
    var_1 = [];

    foreach ( var_3 in var_0 )
    {
        if ( var_3 == self )
            continue;

        if ( _id_0547::_id_5565( var_3._id_0A4B, "zombie_heavy" ) )
            continue;

        var_1 = common_scripts\utility::_id_0F6F( var_1, var_3 );
    }

    foreach ( var_3 in var_1 )
    {
        if ( distancesquared( var_3.origin, self.origin ) < 65536 )
            thread feast_smash_zombie( var_3 );
    }
}

feast_smash_zombie( var_0 )
{
    var_0 _meth_8059( var_0.health + 666, self.origin, undefined, undefined, "MOD_EXPLOSIVE" );
    playfx( common_scripts\utility::_id_44F5( "zmb_guardian_feast_drain" ), self.origin );
    playfx( common_scripts\utility::_id_44F5( "zmb_guardian_feast_drain_death" ), var_0.origin );
    _id_0378::_id_8D74( "dlc3_guardian_smash_feast_zed" );
    var_1 = int( maps\mp\zombies\shotgun\_zombies_shotgun_gamemode_utility::get_difficulty_setting( "guardian_feast_health_regen" ) );

    if ( !isdefined( var_1 ) )
        var_1 = 500;

    if ( self.health + var_1 > self.maxhealth )
        self.health = self.maxhealth;
    else
        self.health = self.health + var_1;
}

feast_smash_close_players()
{
    foreach ( var_1 in level.players )
    {
        var_2 = distancesquared( var_1.origin, self.origin );

        if ( var_2 < 147456 )
            _func_17F( 1 - var_2 / 147456, 0.25, self.origin, 384, var_1 );

        if ( var_2 < 65536 )
            thread feast_smash_player( var_1, var_2 );
    }
}

feast_smash_player( var_0, var_1 )
{
    var_2 = int( _func_2CA( 30, 10, var_1 / 65536 ) );

    if ( !isalive( var_0 ) )
        return;

    if ( _id_0547::_id_577E( var_0 ) )
        return;

    var_0 _meth_809F( "damage_heavy" );
    var_0 _meth_8059( var_2, self.origin, self, undefined, "MOD_CRUSH" );

    if ( isdefined( var_0.health ) && var_0.health - var_2 < 0 )
    {
        var_3 = 5000;
        self.feast_player_kill_count++;

        if ( self.health + var_3 > self.maxhealth )
            self.health = self.maxhealth;
        else
            self.health = self.health + var_3;
    }
}

feast_attract_zombies()
{
    self endon( "guardian_feast_stop" );
    self endon( "death" );
    var_0 = spawnstruct();
    var_0.origin = self.origin;
    level thread feast_clear_attract( self );

    for (;;)
    {
        foreach ( var_2 in _id_0547::_id_4090( "zombie_generic" ) )
        {
            var_2._id_9B61 = var_0;
            var_2._id_173E = 1;
            var_2._id_28D2 = undefined;
            var_2._id_6941 = 1;
        }

        wait 0.5;
    }
}

feast_clear_attract( var_0 )
{
    common_scripts\utility::_id_A70C( var_0, "death", var_0, "guardian_feast_stop" );
    var_1 = _id_0547::_id_4090( "zombie_generic" );

    foreach ( var_3 in var_1 )
    {
        if ( isdefined( var_3._id_9B61 ) )
            var_3._id_9B61 = undefined;
    }
}

guardian_club_gk_vfx_on()
{
    self endon( "death" );
    wait 1;
    self.l_club_vfx = _func_2A8( level._effect["zmb_guardian_club_gk_l"], self, "J_Wrist_LE" );
    maps\mp\agents\_agent_utility::deleteentonagentdeath( self.l_club_vfx );
    self.r_club_vfx = _func_2A8( level._effect["zmb_guardian_club_gk_r"], self, "J_Wrist_RI" );
    maps\mp\agents\_agent_utility::deleteentonagentdeath( self.r_club_vfx );
    self.eyes_vfx = _func_2A8( level._effect["zmb_guardian_eyes_gk"], self, "J_Head" );
    maps\mp\agents\_agent_utility::deleteentonagentdeath( self.eyes_vfx );
    _func_14C( self.l_club_vfx );
    _func_14C( self.r_club_vfx );
    _func_14C( self.eyes_vfx );
    self waittill( "guardian_club_gk_vfx_off" );

    if ( isdefined( self.l_club_vfx ) )
        self.l_club_vfx delete();

    if ( isdefined( self.r_club_vfx ) )
        self.r_club_vfx delete();

    if ( isdefined( self.eyes_vfx ) )
        self.eyes_vfx delete();
}

_________action_plate_drain__________()
{

}

guardian_state_seek_drain()
{
    var_0 = "scripted_grd_seek_plate";
    var_1 = self [[ maps\mp\agents\_agent_utility::_id_0A59( "get_action_params" ) ]]();
    var_2 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_0, var_1 );
    var_3 = [];
    var_3["physMode"] = "gravity";
    maps\mp\agents\humanoid\_humanoid_util::_id_8318( self.origin, self.angles, var_2, undefined, 0, undefined, 0, 0, undefined, undefined, var_3 );
}

guardian_state_seek_drain_cleanup()
{

}

guardian_state_drain()
{
    var_0 = "scripted_grd_stand_node_drain_idle";
    var_1 = self [[ maps\mp\agents\_agent_utility::_id_0A59( "get_action_params" ) ]]();
    var_2 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_0, var_1 );
    maps\mp\agents\humanoid\_humanoid_util::_id_8318( self.origin, self.angles, var_2, undefined, 0, undefined, 1, 1, "guardian_drain_stop", "guardian_drain_stop" );
}

guardian_state_drain_cleanup()
{

}

guardian_state_drain_knockback()
{
    self endon( "death" );
    self endon( "ScriptedAnimationInterrupt" );
    var_0 = "scripted_grd_pain_knockback_back";
    var_1 = self [[ maps\mp\agents\_agent_utility::_id_0A59( "get_action_params" ) ]]();
    var_2 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_0, var_1 );
    var_3 = self _meth_83DB( var_2 );

    if ( isdefined( var_3 ) && var_3 > 0 )
    {
        self.is_downed = 1;
        self _meth_83A2( 1 );
        maps\mp\agents\_scripted_agent_anim_util::_id_8732( 1, "ScriptedAnimation" );
        self _meth_839C( "anim deltas" );
        self _meth_839B( "face angle abs", self.angles );
        self _meth_839A( 1, 1 );
        self _meth_839D( "gravity" );
        var_4 = undefined;
        var_5 = "end";
        guardian_set_damage_limited( 1 );
        self notify( "guardian_club_gk_vfx_off" );
        maps\mp\agents\_scripted_agent_anim_util::_id_71FD( var_2, 0, "scripted_anim", var_5 );
        maps\mp\agents\_scripted_agent_anim_util::_id_8415( var_2, 1, 1, var_4 );
        wait( self.knockdowntime );
        maps\mp\agents\_scripted_agent_anim_util::_id_71FD( var_2, 2, "scripted_anim", var_5 );
        maps\mp\agents\_scripted_agent_anim_util::_id_8732( 0, "ScriptedAnimation" );
        self _meth_83A2( 0 );
        guardian_set_damage_limited( 0 );
        self.is_downed = 0;
    }

    guardian_state_drain_knockback_cleanup();
}

guardian_state_drain_knockback_cleanup()
{
    self.is_downed = 0;
    guardian_set_damage_limited( 0 );
    thread guardian_club_gk_vfx_on();
}

plate_drain_can_drain()
{
    var_0 = 1;

    if ( isdefined( self.last_drain_attempt ) )
    {
        var_1 = self.plate_drain_cooldown_time_min;
        var_2 = self.plate_drain_cooldown_time_max;

        if ( self.health < self.stage3health )
        {
            var_1 = var_1 * 0.75;
            var_2 = var_2 * 0.75;
            self.knockdowntime = 8;
        }

        var_3 = _func_0A5( var_1, var_2 ) * 1000;

        if ( gettime() < self.last_drain_attempt + var_3 )
            var_0 = 0;
    }

    return var_0;
}

guardian_set_damage_limited( var_0 )
{
    if ( common_scripts\utility::_id_562E( var_0 ) )
        self.zombie_limit_damage = self.maxhealth * 0.25;
    else
    {
        self.zombie_limit_damage = undefined;
        self.zombie_guardian_can_take_damage = 1;
    }
}

plate_drain_logic()
{
    self endon( "death" );

    if ( !isdefined( self.myplates ) )
    {
        if ( isdefined( level.dig_objective_assets ) && isdefined( level.dig_objective_assets["blood_plates"] ) )
            self.myplates = level.dig_objective_assets["blood_plates"];
        else
        {
            var_0 = common_scripts\utility::_id_46B7( "blood_plate_struct", "targetname" );

            foreach ( var_2 in var_0 )
            {
                var_3 = common_scripts\utility::_id_44BE( var_2.target, "targetname" );

                foreach ( var_5 in var_3 )
                {
                    var_6 = var_5._id_0165;

                    if ( !isdefined( var_6 ) )
                        continue;

                    switch ( var_6 )
                    {
                        case "plate_model_lower":
                            var_2.plate_model_lower = var_5;
                            break;
                        case "plate_model_upper":
                            var_2.plate_model_upper = var_5;
                            break;
                        case "plate_model":
                            var_2.plate_model = var_5;
                            var_2.model_start_origin = var_5.origin;
                            break;
                        case "plate_trig":
                            var_2.plate_trig = var_5;
                            var_2.plate_trig.associated_struct = var_2;
                            break;
                        case "plate_damage_trig":
                            var_2.plate_damage_trig = var_5;
                            break;
                        case "plate_center_trig":
                            var_2.plate_center_trig = var_5;
                            break;
                    }
                }
            }

            self.myplates = var_0;
        }
    }

    var_9 = plate_drain_chose_plate();
    _id_0547::_id_7D1A( "grd_enter_drain", undefined );
    var_10 = spawnstruct();
    var_10.origin = var_9.origin;
    self._id_1928 = var_10;
    self._id_173E = 1;
    self._id_28D2 = undefined;
    self._id_6941 = 1;
    self.last_plate_chosen = var_9;
    plate_drain_select_orbs();
    plate_drain_move_to_plate( var_9 );
    thread plate_drain_listen_for_orb_damage();
    thread plate_drain_regen_health();
    self.is_draining = 1;
    self.hasnopath = 1;
    self._id_28D2 = undefined;
    self._id_6941 = 0;
    self.enemy_to_attack = undefined;
    self._id_1928 = undefined;
    self.plate_drain_success = undefined;
    level thread plate_drain_fx_handler( var_9, self );
    _id_0378::_id_8D74( "dlc3_guardian_drain_plate_vox" );
    _func_18B( "draining plate" );
    self.num_drain_attempts++;
    waitframe();
    thread _id_0547::_id_7D1A( "grd_drain", undefined, 0.5 );
    var_11 = plate_drain_wait_for_timeout_damage_or_success();
    self.is_draining = 0;
    self.plate_drain_success = undefined;
    _id_0378::_id_8D74( "dlc3_guardian_drain_plate_vox_stop" );
    self.last_drain_attempt = gettime();
    self.drain_queued = 0;

    if ( common_scripts\utility::_id_562E( var_11 ) )
    {
        pulse_perform();
        _id_0378::_id_8D74( "dlc3_guardian_drain_success" );
        self.num_drain_attempts = 0;
        self.is_seeking_drain_point = 0;
        special_set_paused( 0 );
        waitframe();
    }
    else
    {
        waitframe();
        self.num_drain_attempts_failed++;
        _id_0378::_id_8D74( "dlc3_guardian_drain_fail" );
        self.shield_active = 0;
        _id_0547::_id_7D1A( "grd_drain_knockback", undefined, 0.5 );
        self.shield_active = 1;
        self.is_seeking_drain_point = 0;
        guardian_force_enrage();
        special_set_paused( 0 );
    }

    return var_11;
}

plate_drain_select_orbs()
{
    self endon( "death" );
    level.num_orbs_destroyed = 0;
    var_0 = [];
    var_1 = [];
    var_2 = undefined;
    var_3 = _func_18E( "blood_fount_NE", "targetname" );
    var_4 = _func_18E( "blood_fount_SE", "targetname" );
    var_5 = _func_18E( "blood_fount_SW", "targetname" );
    var_6 = _func_18E( "blood_fount_NW", "targetname" );
    var_0 = [ var_3, var_6, var_4, var_5 ];

    foreach ( var_8 in var_0 )
    {
        if ( !isdefined( var_8.face_clip ) || !isdefined( var_8.mouth_struct ) )
        {
            var_9 = common_scripts\utility::_id_44BE( var_8.target, "targetname" );

            foreach ( var_11 in var_9 )
            {
                var_12 = var_11._id_0165;

                if ( !isdefined( var_12 ) )
                    continue;

                switch ( var_12 )
                {
                    case "blood_fount_face_clip":
                        var_8.face_clip = var_11;
                        break;
                    case "blood_fount_mouth":
                        var_8.mouth_struct = var_11;

                        if ( !isdefined( var_8.mouth_beam_end_model ) )
                            var_8.mouth_beam_end_model = var_8.mouth_struct common_scripts\utility::_id_8FFC();

                        break;
                }
            }
        }

        if ( common_scripts\utility::_id_562E( var_8.fount_active ) )
            var_8 notify( "deactivate_orb" );
    }

    waitframe();

    for ( var_15 = 0; var_15 < level.num_orbs; var_15++ )
    {
        var_2 = common_scripts\utility::random( var_0 );
        var_0 = common_scripts\utility::_id_0F93( var_0, var_2 );
        var_1 = common_scripts\utility::_id_0F6F( var_1, var_2 );
    }

    self.founts_to_drain = var_1;
}

plate_drain_chose_plate()
{
    self endon( "death" );
    var_0 = undefined;
    var_1 = [];
    var_2 = self.num_drain_attempts_failed > 2 && level.players.size > 1;
    var_3 = common_scripts\utility::_id_46B7( "guardian_drain_point", "targetname" );

    if ( isdefined( var_3 ) && var_3.size > 0 )
    {
        foreach ( var_5 in var_3 )
        {
            if ( isdefined( var_5.target ) && !isdefined( var_5.plate_center_trig ) )
                var_5.plate_center_trig = _func_18E( var_5.target, "targetname" );

            if ( !isdefined( var_5.plate_model ) )
                var_5.plate_model = var_5 common_scripts\utility::_id_8FFC();
        }

        var_1 = var_3;
    }

    if ( common_scripts\utility::_id_562E( var_2 ) )
        var_1 = common_scripts\utility::_id_0F73( var_1, self.myplates );

    var_0 = common_scripts\utility::_id_4461( self.origin, var_1 );
    return var_0;
}

plate_drain_move_to_plate( var_0 )
{
    self endon( "death" );

    for (;;)
    {
        if ( !isdefined( self._id_1928 ) )
            break;

        if ( distancesquared( self.origin, self._id_1928.origin ) < 1024 )
            break;

        if ( self istouching( var_0.plate_center_trig ) )
            break;

        wait 0.1;
    }

    return;
}

plate_drain_fx_handler( var_0, var_1 )
{
    level thread plate_drain_fx_shield_handler( var_1, var_0 );
    var_2 = common_scripts\utility::_id_0F79( var_1.myplates, var_0 );
    var_1.drain_beams = [];

    if ( common_scripts\utility::_id_562E( var_2 ) )
    {
        var_3 = _func_382( "zmb_geistkraft_blood_beam_guardian", var_0.plate_model, "TAG_ORIGIN", var_1, "j_Spine4" );
        var_1.drain_beams = common_scripts\utility::_id_0F6F( var_1.drain_beams, var_3 );
    }
    else if ( isdefined( var_1.founts_to_drain ) && var_1.founts_to_drain.size > 0 )
    {
        foreach ( var_5 in var_1.founts_to_drain )
        {
            var_3 = _func_382( "zmb_geistkraft_blood_beam_guardian", var_5.mouth_beam_end_model, "TAG_ORIGIN", var_1, "j_Spine4" );
            var_1.drain_beams = common_scripts\utility::_id_0F6F( var_1.drain_beams, var_3 );
        }
    }

    var_1 common_scripts\utility::_id_A70A( "death", "guardian_drain_stop" );

    if ( isdefined( var_1 ) && isdefined( var_1.drain_beams ) && var_1.drain_beams.size > 0 )
    {
        foreach ( var_3 in var_1.drain_beams )
            var_3 delete();

        var_1.drain_beams = [];
    }

    level notify( "deactivate_all_orbs" );
}

plate_drain_fx_shield_handler( var_0, var_1 )
{
    var_2 = _func_14B( common_scripts\utility::_id_44F5( "dlc_zmb_dig02_boss_shield" ), var_0.origin );
    _func_14C( var_2 );

    for (;;)
    {
        var_3 = var_0 common_scripts\utility::_id_A715( "guardian_drain_stop", "death", "grd_orb_destroyed" );

        if ( _id_0547::_id_5565( var_3, "grd_orb_destroyed" ) )
        {
            if ( !isdefined( level.num_orbs_destroyed ) )
                level.num_orbs_destroyed = 0;

            level.num_orbs_destroyed++;

            if ( level.num_orbs_destroyed >= level.num_orbs )
                break;
        }
        else
            break;
    }

    if ( isdefined( var_2 ) )
        var_2 delete();

    if ( isalive( var_0 ) )
    {
        playfx( common_scripts\utility::_id_44F5( "dlc_zmb_dig02_boss_shield_burst" ), var_0 gettagorigin( "Tag_Origin" ), anglestoforward( var_0.angles ) );
        var_0.drain_shielded = 0;
        var_0.drain_damage = 0;
        var_0 notify( "guardian_drain_stop", "ko" );
    }
}

plate_drain_wait_for_timeout_damage_or_success()
{
    self endon( "death" );
    var_0 = 1;
    var_1 = common_scripts\utility::_id_A719( 15, "guardian_drain_stop" );

    if ( _id_0547::_id_5565( var_1[0], "timeout" ) )
    {
        if ( isdefined( self.plate_drain_success ) )
        {
            if ( self.plate_drain_success )
            {
                self notify( "guardian_drain_stop", "finished" );
                level notify( "guardian_drain_stop" );
                var_0 = 1;
            }
            else
            {
                self notify( "guardian_drain_stop", "ko" );
                level notify( "guardian_drain_stop" );
                var_0 = 0;
            }
        }
        else
        {
            self notify( "guardian_drain_stop", "finished" );
            level notify( "guardian_drain_stop" );
            var_0 = 1;
        }
    }
    else if ( _id_0547::_id_5565( var_1[0], "guardian_drain_stop" ) )
    {
        if ( _id_0547::_id_5565( var_1[1], "ko" ) )
            var_0 = 0;
        else
            var_0 = 1;
    }

    return var_0;
}

plate_drain_listen_for_orb_damage()
{
    self endon( "death" );

    foreach ( var_1 in self.founts_to_drain )
    {
        if ( !common_scripts\utility::_id_562E( var_1.fount_active ) )
            var_1 thread plate_drain_orb_wait_for_destruction( self );
    }
}

plate_drain_orb_wait_for_destruction( var_0 )
{
    self.fount_active = 1;
    self._id_3F3F = _func_2A8( common_scripts\utility::_id_44F5( "dlc_zmb_dig02_statue_gk_shield" ), self, "TAG_ORIGIN" );
    _func_14C( self._id_3F3F );
    self.face_clip _meth_82C1();
    self.face_clip _meth_82C3( 1 );
    self.face_clip _meth_849F( 1 );
    self.face_clip.total_damage = 0;
    self.face_clip.my_fount = self;
    self.face_clip.damagecallback = ::plate_drain_orb_on_damage;
    [var_2, var_3] = common_scripts\utility::_id_A70E( self, "orb_destroyed", var_0, "death", level, "deactivate_all_orbs", self, "deactivate_orb" );

    if ( _id_0547::_id_5565( var_2, "orb_destroyed" ) && _id_0547::_id_5565( var_3, self ) )
    {
        if ( isdefined( var_0 ) && isalive( var_0 ) )
        {
            var_4 = 2000;

            if ( common_scripts\utility::_id_562E( level.zmb_red_skull_mode_activated ) )
                var_4 = var_4 * 0.75;

            if ( isdefined( var_0.drain_end_time ) )
                var_0.drain_end_time = var_0.drain_end_time + var_4;

            var_0 notify( "grd_orb_destroyed" );
        }
    }

    self._id_3F3F delete();
    self.face_clip _meth_82C2();
    self.face_clip _meth_82C3( 0 );
    self.face_clip _meth_849F( 0 );
    self.face_clip.damagecallback = undefined;
    playfx( common_scripts\utility::_id_44F5( "zmb_hilt_sphere_explosion" ), self.mouth_struct.origin, anglestoforward( self.mouth_struct.angles ) );
    self.fount_active = 0;
}

plate_drain_orb_on_damage( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    if ( isplayer( var_1 ) )
    {
        var_12 = "weakpoint";
        var_1 thread _id_04C7::_id_A102( var_12 );
        self.total_damage = self.total_damage + var_2;

        if ( self.total_damage > level.guardian_plate_damage_limit )
            self.my_fount notify( "orb_destroyed" );
    }
}

plate_drain_regen_health()
{
    self endon( "death" );
    self endon( "guardian_drain_stop" );
    var_0 = plate_drain_get_target_health();
    var_1 = gettime();
    var_2 = 10;

    if ( common_scripts\utility::_id_562E( level.zmb_red_skull_mode_activated ) )
    {
        switch ( level.players.size )
        {
            case 1:
                var_2 = 10;
                break;
            case 2:
                var_2 = 9;
                break;
            case 3:
                var_2 = 8;
                break;
            case 4:
                var_2 = 7;
                break;
        }
    }

    self.drain_end_time = var_1 + var_2 * 1000;
    var_3 = int( ( var_0 - self.health ) / var_2 * 0.25 );

    for (;;)
    {
        if ( self.health + var_3 >= self.maxhealth )
            self.health = self.maxhealth;
        else
            self.health = self.health + var_3;

        if ( gettime() >= self.drain_end_time )
        {
            self.plate_drain_success = 1;
            self notify( "guardian_drain_stop", "finished" );
        }

        wait 0.25;
    }
}

plate_drain_get_target_health()
{
    var_0 = 0.25;

    if ( common_scripts\utility::_id_562E( level.zmb_red_skull_mode_activated ) )
    {
        switch ( level.num_orbs )
        {
            case 1:
                var_0 = 0.25;
                break;
            case 2:
                var_0 = 0.3;
                break;
            case 3:
                var_0 = 0.33;
                break;
            case 4:
                var_0 = 0.4;
                break;
        }
    }

    var_1 = self.health + int( self.maxhealth * var_0 );

    if ( var_1 > self.maxhealth )
        var_1 = self.maxhealth;

    return var_1;
}

_________action_pulse__________()
{

}

guardian_state_pulse()
{
    self endon( "death" );
    thread pulse_absorb_zombies();
    thread pulse_absorb_players();
    thread pulse_do_fx();
    guardian_set_damage_limited( 1 );
    var_0 = "stand_consume";
    var_1 = self [[ maps\mp\agents\_agent_utility::_id_0A59( "get_action_params" ) ]]();
    var_2 = maps\mp\agents\_scripted_agent_anim_util::_id_087C( var_0, var_1 );
    maps\mp\agents\humanoid\_humanoid_util::_id_8318( self.origin, self.angles, var_2, undefined, 0, undefined, 1 );
    guardian_state_pulse_cleanup();
}

guardian_state_pulse_interrupt()
{
    guardian_state_pulse_cleanup();
}

guardian_state_pulse_cleanup()
{
    guardian_set_damage_limited( 0 );
    self.is_pulsing = 0;
    special_schedule_next();
}

pulse_perform()
{
    if ( common_scripts\utility::_id_562E( self.is_pulsing ) || common_scripts\utility::_id_562E( self.is_feasting ) )
    {
        special_schedule_next();
        return;
    }

    self.is_pulsing = 1;
    _id_0547::_id_7D1A( "grd_pulse" );
}

pulse_do_fx()
{
    var_0 = _func_14B( level._effect["dlc_zmb_dig02_pulse_radius_250"], self.origin );
    _id_0378::_id_8D74( "guardian_pulse" );
    _func_14C( var_0 );
    _id_0378::_id_8D74( "dlc3_guardian_pulse" );
    wait 3;
    var_0 delete();
}

pulse_absorb_zombies()
{
    var_0 = _id_0547::_id_4090( "zombie_generic" );
    var_1 = common_scripts\utility::_id_40B0( self.origin, var_0, undefined, undefined, 250 );

    foreach ( var_3 in var_1 )
        pulse_absorb_kill( var_3 );
}

pulse_absorb_players()
{
    self endon( "death" );
    wait 1;
    var_0 = 3;

    foreach ( var_2 in level.players )
        thread pulse_attempt_player_absorb( var_2, var_0 );
}

pulse_attempt_player_absorb( var_0, var_1 )
{
    var_0 endon( "death" );
    self endon( "death" );

    if ( _id_0547::_id_577E( var_0 ) )
        return;

    var_2 = 262144;
    var_3 = 65536;
    var_4 = var_0.origin + ( 0, 0, 32 );
    var_5 = self.origin + ( 0, 0, 32 );
    var_6 = 500;
    var_7 = -0.5;
    var_8 = 20;
    var_9 = distancesquared( var_4, var_5 );
    var_10 = _func_07E( var_4, var_5, 0, self, var_0 );

    if ( var_9 >= var_2 )
        return;

    var_11 = var_1 * ( _func_211( self.origin, var_0.origin ) / var_2 );
    var_12 = var_1 * ( _func_211( self.origin, var_0.origin ) / var_2 );
    var_0 _meth_8182( "zm_heavy_hit", var_12 * 1.4, var_11 );
    var_0 _meth_8308( 0 );
    var_0 _meth_809F( "damage_heavy" );

    if ( common_scripts\utility::_id_562E( var_10 ) )
    {
        if ( var_9 > var_3 )
        {
            thread pulse_drag_in_player( var_0 );
            var_0 _meth_8059( var_8, self.origin, self, self, "MOD_CRUSH" );
        }
        else
        {
            var_0 _meth_8059( var_8, self.origin, self, self, "MOD_CRUSH" );
            var_0 _id_0533::_id_0F37( var_7, 1, 1 );
        }
    }
    else
    {

    }

    wait( var_1 - 1 );
    var_0 _meth_8308( 1 );
}

pulse_can_hit_player( var_0 )
{
    if ( _id_0547::_id_577E( var_0 ) )
        return 0;

    var_1 = 262144;
    var_2 = 65536;
    var_3 = var_0.origin + ( 0, 0, 32 );
    var_4 = self.origin + ( 0, 0, 32 );
    var_5 = distancesquared( var_3, var_4 );
    var_6 = _func_07E( var_3, var_4, 0, self, var_0 );

    if ( var_5 >= var_1 || !common_scripts\utility::_id_562E( var_6 ) )
        return 0;

    return 1;
}

pulse_drag_in_player( var_0 )
{
    var_0 endon( "death" );
    self endon( "death" );
    var_1 = 550;
    var_2 = self.origin - var_0.origin;
    var_2 = ( var_2[0], var_2[1], 0 );
    var_2 = var_1 * vectornormalize( var_2 );
    var_2 = ( var_2[0], var_2[1], 125 );
    var_0 _meth_82F7( var_2 );
}

pulse_absorb_kill( var_0 )
{
    self endon( "death" );

    if ( !_func_1EF( var_0 ) || !isalive( var_0 ) || var_0 _meth_85A5() != "zombie_animclass" || common_scripts\utility::_id_562E( var_0.transformingtosizzler ) )
    {
        if ( isdefined( var_0 ) && isalive( var_0 ) )
            var_0 suicide();
    }
    else
    {
        var_1 = [ "TAG_WEAPON_LEFT", "TAG_WEAPON_RIGHT" ];
        var_2 = common_scripts\utility::random( var_1 );
        _func_147( level._effect["dlc_zmb_dig02_pulse_shock"], var_0, "Tag_Origin" );

        if ( isdefined( var_0 ) && isalive( var_0 ) )
            var_0 suicide();
    }

    var_3 = 200;

    if ( common_scripts\utility::_id_562E( level.zmb_red_skull_mode_activated ) )
        var_3 = 400;

    if ( self.health + var_3 > self.maxhealth )
        self.health = self.maxhealth;
    else
        self.health = self.health + var_3;
}

bomb_sabotage_func( var_0, var_1, var_2 )
{
    var_3 = self.maxhealth * 0.25 / level.players.size;
    self _meth_8059( var_3, var_0.origin, var_0, var_0, var_2, var_1 );
}
