// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{

}

hilt_get_weapon_name()
{
    return "hilt_zm";
}

hilt_give_hilt()
{
    _id_0586::_id_078C( "hilt_zm" );
    _id_0586::_id_078E( "hilt_zm" );
}
